# Validate SVG's & build artifact with PNG's
name: validate

# Triggers for the workflow to run
on:
  # Triggers the workflow on push or pull request events but only for the "master" and "develop" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Jobs to run on trigger
jobs:
  # Validate
  test:
    runs-on: ubuntu-latest
    steps:
      
      # Environment
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      # Dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Generate icons & validate icons
      - name: Validate all icons and metadata
        id: validation
        run: python scripts/validate.py
